services:
  backend:
    image: ghcr.io/gmazoyer/reflet:latest
    volumes:
      - ./config.toml:/etc/reflet/config.toml:ro
    ports:
      - "8080:8080"
      - "179:179"
    restart: unless-stopped

  frontend:
    image: ghcr.io/gmazoyer/reflet-frontend:latest
    environment:
      - BACKEND_URL=http://backend:8080
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: unless-stopped
